#ifndef PORTAL300_H
#define PORTAL300_H

// Identifiers for doors:

#define DOOR_B  "b"
#define DOOR_B2 "b2"
#define DOOR_C  "c"
#define DOOR_C2 "c2"

#define DOOR_NAME(_Door) "door." _Door

#define PORTAL300_TOPIC_PREFIX "shackspace/portal/"

////////////////////////////////////////////////////////////////////////////////
// events:
// Events are messages that are produced by external means (sensors, ssh, ...).

#define PORTAL300_TOPIC_EVENT_DOORBELL PORTAL300_TOPIC_PREFIX "event/doorbell" // payload: door name that triggered the event
#define PORTAL300_TOPIC_EVENT_BUTTON   PORTAL300_TOPIC_PREFIX "event/button"   // payload: door name that triggered the event

////////////////////////////////////////////////////////////////////////////////
// actions:
// Actions are generated by the system and require work to be done.

#define PORTAL300_TOPIC_ACTION_OPEN_DOOR_SAFE   PORTAL300_TOPIC_PREFIX "action/door/open-safe"   // payload: door name that should be opened
#define PORTAL300_TOPIC_ACTION_OPEN_DOOR_UNSAFE PORTAL300_TOPIC_PREFIX "action/door/open-unsafe" // payload: door name that should be opened
#define PORTAL300_TOPIC_ACTION_LOCK_DOOR        PORTAL300_TOPIC_PREFIX "action/door/lock"        // payload: door name that should be closed

////////////////////////////////////////////////////////////////////////////////
// system status:
// Status messages generated by systems when they go online/offline

// payload:
#define PORTAL300_STATUS_SYSTEM_OFFLINE "offline"
#define PORTAL300_STATUS_SYSTEM_ONLINE  "online"

// topics:
#define PORTAL300_TOPIC_STATUS_SSH_INTERFACE   PORTAL300_TOPIC_PREFIX "status/ssh-interface"   // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_CONTROL_B2 PORTAL300_TOPIC_PREFIX "status/door-control-b2" // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_CONTROL_C2 PORTAL300_TOPIC_PREFIX "status/door-control-c2" // payload: see above
#define PORTAL300_TOPIC_STATUS_BUSCH_INTERFACE PORTAL300_TOPIC_PREFIX "status/busch-interface" // payload: see above

////////////////////////////////////////////////////////////////////////////////
// door status:
// Status messages generated by doors when they change their state

// payload:
#define PORTAL300_STATUS_DOOR_LOCKED "locked"
#define PORTAL300_STATUS_DOOR_CLOSED "closed"
#define PORTAL300_STATUS_DOOR_OPENED "opened"

// topics:
#define PORTAL300_TOPIC_STATUS_DOOR(_Door) PORTAL300_TOPIC_PREFIX "status/door-" _Door // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_B2     PORTAL300_TOPIC_STATUS_DOOR(DOOR_B2)
#define PORTAL300_TOPIC_STATUS_DOOR_C2     PORTAL300_TOPIC_STATUS_DOOR(DOOR_C2)

#endif