#ifndef PORTAL300_H
#define PORTAL300_H

// Identifiers for doors:

#define DOOR_B  B
#define DOOR_B2 B2
#define DOOR_C  C
#define DOOR_C2 C2

#define DOOR_NAME(_Door) "door." #_Door

////////////////////////////////////////////////////////////////////////////////
// events:
// Events are messages that are produced by external means (sensors, ssh, ...).

#define PORTAL300_TOPIC_EVENT_DOORBELL      "shackspace/portal/event/doorbell"      // payload: door name that triggered the event
#define PORTAL300_TOPIC_EVENT_CLOSE_REQUEST "shackspace/portal/event/close-request" // payload: door name that triggered the event

////////////////////////////////////////////////////////////////////////////////
// actions:
// Actions are generated by the system and require work to be done.

#define PORTAL300_TOPIC_ACTION_OPEN_DOOR  "shackspace/portal/action/door/open"  // payload: door name that should be opened
#define PORTAL300_TOPIC_ACTION_CLOSE_DOOR "shackspace/portal/action/door/close" // payload: door name that should be closed

////////////////////////////////////////////////////////////////////////////////
// system status:
// Status messages generated by systems when they go online/offline

// payload:
#define PORTAL300_STATUS_SYSTEM_OFFLINE "offline"
#define PORTAL300_STATUS_SYSTEM_ONLINE  "online"

// topics:
#define PORTAL300_TOPIC_STATUS_SSH_INTERFACE   "shackspace/portal/status/ssh-interface"   // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_CONTROL_B2 "shackspace/portal/status/door-control-b2" // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_CONTROL_C2 "shackspace/portal/status/door-control-c2" // payload: see above
#define PORTAL300_TOPIC_STATUS_BUSCH_INTERFACE "shackspace/portal/status/busch-interface" // payload: see above

////////////////////////////////////////////////////////////////////////////////
// door status:
// Status messages generated by doors when they change their state

// payload:
#define PORTAL300_STATUS_DOOR_LOCKED "locked"
#define PORTAL300_STATUS_DOOR_CLOSED "closed"
#define PORTAL300_STATUS_DOOR_OPENED "opened"

// topics:
#define PORTAL300_TOPIC_STATUS_DOOR_B2 "shackspace/portal/status/door-b2" // payload: see above
#define PORTAL300_TOPIC_STATUS_DOOR_C2 "shackspace/portal/status/door-c2" // payload: see above

#endif