

all:
	@echo "This makefile provides the following targets:"
	@echo ""
	@echo "- regenerate: Regenerates all key headers"

regenerate:
	./make-cheader.py \
		busch-interface/main/certs/client.crt \
		door-control/main/certs/client.crt \
		busch-interface/main/certs/client.key \
		door-control/main/certs/client.key \
		busch-interface/main/certs/ca.crt \
		door-control/main/certs/ca.crt


